//
//  MKChainedClassConst.h
//  ObjectCChained
//
//  Created by sny on 2018/5/22.
//  Copyright © 2018年 HuangYangYang. All rights reserved.
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>

//传入参数的数据类型
UIKIT_EXTERN NSString * const  MKCLHAINEDCLASS_PROPERTY_TYPE_NSSRTING;
UIKIT_EXTERN NSString * const  MKCLHAINEDCLASS_PROPERTY_TYPE_NSSARRAY;
UIKIT_EXTERN NSString * const  MKCLHAINEDCLASS_PROPERTY_TYPE_NSNUMBER;
UIKIT_EXTERN NSString * const  MKCLHAINEDCLASS_PROPERTY_TYPE_MODEL;

//传入参数对象或者数组内的元素的类型(基本类型)

UIKIT_EXTERN char *   MKCLHAINEDCLASS_PROPERTY_TYPE_INT;
UIKIT_EXTERN char *   MKCLHAINEDCLASS_PROPERTY_TYPE_CHAR;
UIKIT_EXTERN char *   MKCLHAINEDCLASS_PROPERTY_TYPE_SHORT;
UIKIT_EXTERN char *   MKCLHAINEDCLASS_PROPERTY_TYPE_LONG;
UIKIT_EXTERN char *   MKCLHAINEDCLASS_PROPERTY_TYPE_UNSIGNEDCHAR;
UIKIT_EXTERN char *   MKCLHAINEDCLASS_PROPERTY_TYPE_UNSIGNEDINT;
UIKIT_EXTERN char *   MKCLHAINEDCLASS_PROPERTY_TYPE_UNSIGNEDSHORT;
UIKIT_EXTERN char *   MKCLHAINEDCLASS_PROPERTY_TYPE_UNSIGNEDLONG;
UIKIT_EXTERN char *   MKCLHAINEDCLASS_PROPERTY_TYPE_FLOAT;
UIKIT_EXTERN char *   MKCLHAINEDCLASS_PROPERTY_TYPE_DOUBLE;
UIKIT_EXTERN char *   MKCLHAINEDCLASS_PROPERTY_TYPE_BOOL;
UIKIT_EXTERN char *   MKCLHAINEDCLASS_PROPERTY_TYPE_VOID;
UIKIT_EXTERN char *   MKCLHAINEDCLASS_PROPERTY_TYPE_CHARALL;
UIKIT_EXTERN char *   MKCLHAINEDCLASS_PROPERTY_TYPE_ID;
UIKIT_EXTERN char *   MKCLHAINEDCLASS_PROPERTY_TYPE_CLASS;
UIKIT_EXTERN char *   MKCLHAINEDCLASS_PROPERTY_TYPE_SEL;

//字符串的比较
#define MKChainedClass_Compare(currentString,compareString) [[NSString stringWithFormat:@"%c",currentString] isEqualToString:[NSString stringWithFormat:@"%s",compareString]]


@interface MKChainedClassConst : NSObject

@end
